name = "Sha3"
version = "0.1.0"
defaultTargets = ["Sha3", "Cli"]
testDriver = "Test"

[[lean_lib]]
name = "Sha3"

# [[lean_lib]]
# name = "Test"
# extraDepTargets = ["Sha3"]

[[lean_exe]]
name = "Test"
srcDir = "Test"
root = "Main"

[[lean_exe]]
name = "Cli"
srcDir = "Sha3"
root = "Cli"

[[require]]
name = "aeneas"
path = "/home/ayhon/inria/aeneas/backends/lean"
