name = "Sha3"
version = "0.1.0"
defaultTargets = ["Sha3", "Cli"]
testDriver = "TestExec"

[[lean_lib]]
name = "Sha3"

[[lean_lib]]
name = "Test"
extraDepTargets = ["Sha3"]

[[lean_exe]]
name = "TestExec"
srcDir = "Sha3/Test"
root = "Main"

[[lean_exe]]
name = "Cli"
srcDir = "Sha3"
root = "Cli"

[[require]]
name = "aeneas"
git = { url = "https://github.com/ayhon/aeneas", subDir = "backends/lean" }
rev = "ad86950"
