name = "Sha3"
version = "0.1.0"
defaultTargets = ["Sha3"]
testDriver = "Test"

[[lean_lib]]
name = "Sha3"

[[lean_exe]]
name = "Test"

# [[require]]
# name = "mathlib"
# git = "https://github.com/leanprover-community/mathlib4"
# rev = "v4.17.0"
